# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RealAppTest' do

  pod 'AppAnalyticsObjC', :git => 'https://github.com/appanalytic/lib-objective-c.git'

end
